### PR TITLE
Last-minute 841 change

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by tomhschmidt** [comment]
Hey Will -- can you also make these changes in the root index.html? The build system on this repo is a little wonky. Been meaning to fix.

**Comment by fulldecent** [comment]
I didn't forget about this. We may have one or two small wording changes. I will check back when the dust settles. This is NOTHING major at all.

**Comment by fulldecent** [comment]
There will be more changes. But this is ready to go now.

Sorry I broke your formatting. Using standard Solidity 4-space indent now.

**Comment by tomhschmidt** [comment]
Looks like this conflicts with the old root / non-docs build system. Want to move over to the new build system and I can merge this?

**Comment by fulldecent** [comment]
Rebased. Updated. Ready to merge.

**Comment by fulldecent** [comment]
You can review with `git diff -b`

**Pull request merged**
